### ISSUE TITLE
Error: Command failed: at ChildProcess.exithandler

### ISSUE THREAD

**Issue by anil1712** [cgreening/node-seoserver#4]
Hi, sometimes its throwing this type of exception on browser as well as on command prompt.

```
Error: Command failed: at ChildProcess.exithandler (child_process.js:637:15) 
at ChildProcess.EventEmitter.emit (events.js:98:17) at maybeClose 
(child_process.js:735:16) at Process.ChildProcess._handle.onexit 
(child_process.js:802:5)
```

**Comment by cgreening** [comment]
Sounds like either the phantomjs is crashing or timing out. You could try increasing the timeout in the config file or run phantomjs from the command line on the pages that it is crashing on and see if you can recreate the issue.
