### ISSUE TITLE
Not working in Ubuntu

### ISSUE THREAD

**Issue by anil1712** [cgreening/node-seoserver#5]
Hi, I have successfully install the same on my W8 system but got problem while installing the same on `Ubuntu` its throwing exception like this:

```
npm http GET https://registry.npmjs.org/express/3.4.8
npm http GET https://registry.npmjs.org/tmp
npm http GET https://registry.npmjs.org/phantomjs
npm http GET https://registry.npmjs.org/config
npm http GET https://registry.npmjs.org/colors
```

   npm ERR! Error: failed to fetch from registry: tmp
   npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
   npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
   npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-   client/request.js:136:18)
   npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
   npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
   ......................etc...

Please give some solution for this.

**Comment by cgreening** [comment]
I don't think this is an issue with node-seoserver - I can't help you with this one as it looks like a problem with npm on your machine.

**Comment by anil1712** [comment]
ok thanks.
