### ISSUE TITLE
Error: Command failed: /bin/sh: 1: render_desktop_phantom.js

### ISSUE THREAD

**Issue by anil1712** [cgreening/node-seoserver#6]
While browsing the url by bot it throws some exception like this.

```
Error: Command failed: /bin/sh: 1: render_desktop_phantom.js: not found at 
ChildProcess.exithandler (child_process.js:282:15) at ChildProcess.emit 
(events.js:70:17) at maybeExit (child_process.js:362:16) at Socket.<anonymous> 
(child_process.js:467:7) at Socket.emit (events.js:67:17) at Array.1 (net.js:335:10) at 
EventEmitter._tickCallback (node.js:190:39)
```

Please try to give some solution for this.

**Comment by cgreening** [comment]
Do you have the render_desktop_phantom.js file in the same directory as the seoserver.js?

**Comment by anil1712** [comment]
Yes, I didn't made any changes on any files.
Have you tried the same on `Linux/Ubuntu` , Can you tell me which `node` and `npm` version you are using.?

**Comment by anil1712** [comment]
Was some problem in my node and npm version, Now it is fixed
